name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: ^7.0

      - name: Install Deps
        run: pnpm i

      # build all packages
      - name: Build 🔧
        run: pnpm run build

      # build react-vite
      - name: Build-vite 🔧
        run: cd packages/react-vite && pnpm run build_github_ci

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: packages/react-vite/dist # The folder the action should deploy.
